// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"alfred/app/model/internal"
)

// Bodyinfo is the golang structure for table bodyinfo.
type Bodyinfo internal.Bodyinfo

// Fill with you ideas below.
