// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"alfred/app/model/internal"
)

// Password is the golang structure for table password.
type Password internal.Password

// Fill with you ideas below.
