// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"alfred/app/model/internal"
)

// Permission is the golang structure for table permission.
type Permission internal.Permission

// Fill with you ideas below.
