// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"alfred/app/model/internal"
)

// PwdCompany is the golang structure for table pwd_company.
type PwdCompany internal.PwdCompany

// Fill with you ideas below.
