// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Bodyinfo is the golang structure for table bodyinfo.
type Bodyinfo struct {
	ID          uint `orm:"ID,primary"  json:"iD"`          //
	Height      int  `orm:"Height"      json:"height"`      //
	Weight      int  `orm:"Weight"      json:"weight"`      //
	FatRatio    int  `orm:"FatRatio"    json:"fatRatio"`    //
	MuscleRatio int  `orm:"MuscleRatio" json:"muscleRatio"` //
}
