// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Bodyinfo is the golang structure for table bodyinfo.
type Bodyinfo struct {
	ID          uint        `orm:"ID,primary"  json:"iD"`          //
	Height      int         `orm:"Height"      json:"height"`      //
	Weight      int         `orm:"Weight"      json:"weight"`      //
	FatRatio    float64     `orm:"FatRatio"    json:"fatRatio"`    //
	MuscleRatio float64     `orm:"MuscleRatio" json:"muscleRatio"` //
	RecordDate  *gtime.Time `orm:"RecordDate"  json:"recordDate"`  //
	UserID      uint        `orm:"UserID"      json:"userID"`      //
}
