// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Password is the golang structure for table password.
type Password struct {
	ID       uint   `orm:"ID,primary" json:"iD"`       //
	Account  string `orm:"Account"    json:"account"`  //
	Password string `orm:"Password"   json:"password"` //
	Level    int    `orm:"Level"      json:"level"`    //
	WebName  string `orm:"WebName"    json:"webName"`  //
	Company  int    `orm:"Company"    json:"company"`  //
	Remark   string `orm:"Remark"     json:"remark"`   //
}
