// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Permission is the golang structure for table permission.
type Permission struct {
	Id         int    `orm:"id,primary" json:"id"`         //
	Type       int    `orm:"type"       json:"type"`       //
	Permission string `orm:"permission" json:"permission"` //
}
