// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Permission is the golang structure for table permission.
type Permission struct {
	Type       int    `orm:"type,primary" json:"type"`       //
	Permission string `orm:"permission"   json:"permission"` //
}
