// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// User is the golang structure for table user.
type User struct {
	ID             uint   `orm:"ID,primary"     json:"iD"`             //
	Identification string `orm:"Identification" json:"identification"` //
	Password       string `orm:"Password"       json:"password"`       //
	NickName       string `orm:"NickName"       json:"nickName"`       //
	Permission     int    `orm:"Permission"     json:"permission"`     //
}
