# HTTP Server
[server]
    address        = ":8001"
    serverRoot     = "public"
    serverAgent    = "gf-alfred"
    logPath        = "/var/log/alfred/"
    nameToUriType  = 2
    routeOverWrite = true

# Logger.
[logger]
    Path        = "/var/log/alfred/"
    Level       = "all"
    Stdout      = true
    file        = "{Y-m-d}.log"

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:123456@tcp(192.168.171.128:3306)/alfred"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/var/log/alfred/sql"
        Level  = "all"
        Stdout = true

# 编译配置文件
[compiler]
     name     = "alfred" #编译后的文件名称
     version  = "1.0.0" #编译后的文件会生成到/bin/1.0.0目录里
     arch     = "386,amd64"
     system   = "linux,windows,darwin"
     output   = ""
     path     = "./bin"  #输出到bin目录
     extra    = "-ldflags \"-s -w\""
     # 自定义编译时内置变量
     [compiler.VarMap]
         author = "zhaoxiang"
         email  = "18671056539@163.com"

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link    = "mysql:root:123456@tcp(192.168.171.128:3306)/alfred"