// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"alfred/app/dao/internal"
)

// passwordDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type passwordDao struct {
	internal.PasswordDao
}

var (
	// Password is globally public accessible object for table password operations.
	Password = passwordDao{
		internal.Password,
	}
)

// Fill with you ideas below.
