// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"alfred/app/dao/internal"
)

// pwdCompanyDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type pwdCompanyDao struct {
	internal.PwdCompanyDao
}

var (
	// PwdCompany is globally public accessible object for table pwd_company operations.
	PwdCompany = pwdCompanyDao{
		internal.PwdCompany,
	}
)

// Fill with you ideas below.
